apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  labels:
    app: embedding-service
spec:
  replicas: 1                 # scale up if needed
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
    spec:
      containers:
      - name: embedding
        image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/embedding-service:latest
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "3000m"
            memory: "6Gi"
          requests:
            cpu: "900m"
            memory: "2Gi"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
spec:
  selector:
    app: embedding-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP